### ISSUE TITLE
extract epk (webOS LG TV)

### ISSUE THREAD

**Issue by sasha310813** [openlgtv/epk2extract#1]
I don't know if it's the right place to write. I'd like to ask you if it's possible to extract webOS LG TV epk (V3), my TV is 55EC930V. If yes, how to do it? From what I understand I need the keys to extract the epk firmware file. How can I get these keys? THANK YOU!!!

**Comment by Umeaboy** [comment]
1. Purchase the service manual for it from here: http://www.manualzone.com/repair-service-manuals/LG/55EC930V/RWSPFM-58812433-1
2. Find the EMMC pinouts in that manual and then you need to find a way to dump the keys from the memory card.

**Comment by Umeaboy** [comment]
Download the source code for epkextract. Check that all the dependancies in your dist is installed and then run ./build.sh in the epk2extract folder to compile and build it. Then run ./epk2extract starfish-dvb-secured-m14tv-25.ashley.m14tv-2518-05.05.01-prodkey_usb.oled_V3_SECURED.epk as root. Voila! The EPK is now extracted. :)
