### ISSUE TITLE
MTK Crypted header not found

### ISSUE THREAD

**Issue by apeppels** [openlgtv/epk2extract#14]
I'm having some trouble unpacking the new firmware for a Philips 43PUS6162 using your (so far excellent) tool and the recovered AES keys.

The general header seems to get decrypted just fine with the key 
09291094092910940929109409291094
As an aside: it seems to be a alternate version of the MediaTek packages with a different vendor magic:

```
[+] Found UNKNOWN Package (Magic: 'TPV')
 >54505600 23444840 4669526D 54504D31< TPV.#DH@FiRmTPM1 00000000

```

After adding the magic to mtk_package.h I'm unfortunately not able to decrypt the rest of the package headers to find MTK_RESERVED_MAGIC.

```
PAK #1 [ENCRYPTED] (name='ixml', offset='0x14c', size='32708 bytes')
--snip--
[!] WARNING: MTK Crypted header not found, continuing anyways...
```
As expected, the packages start off with the 4 bytes name, the 4 bytes set to 00000001, and the length. The 16 bytes that follow are the same for every PAK: I suspect this is still the MTK_RESERVED_MAGIC:

```
00000110  69 78 6d 6c 01 00 00 00  c4 7f 00 00 ca a2 df 9f  |ixml............|
00000120  47 51 ad 1f 96 80 df db  92 06 de 42 71 82 73 72  |GQ.........Bq.sr|

00402bf6  72 6f 6f 74 01 00 00 00  00 d0 e8 04 ca a2 df 9f  |root............|
00402c06  47 51 ad 1f 96 80 df db  92 06 de 42 b8 f2 a0 16  |GQ.........B....|
```
So in my situation I expect 
`ca a2 df 9f 47 51 ad 1f 96 80 df db  92 06 de 42`
to decrypt to 
`reserved mtk inc`
However it fails to decrypt to anything legible, let alone the expected header. I have tried both the recovered AES and its md5sum [as described here](http://neophob.com/2010/01/root-my-tv-hack-philips-pfl9703/#comment-2507) to no avail.

Any ideas about what I'm overlooking?

FIRMWARE:
```
https://www.p4c.philips.com/files/4/43pus6162_12/43pus6162_12_fus_eng.zip
http://firmware.nettvservices.com/firmware/prod/5/TPM177E00001/201475785/20180522/Autorun.upg
```
IV
	`A29DBF8608F187481D69290A478EFA84`
md5sum: 
        `cc6e6d8e3245bc66d98d60fa80ddca6b`

AESKEY
	`88143AC13412B726CC5B9D2F004A7B0A`
md5sum: 
        `9020c2c61fe496d94b3a0519af1c15f2`

Pubkey
```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwWorAywjRi7gDWOtGOlv
/yhrkk9qAHM5d0dRRBabwagnvtt/WRbBMowmTRY4w7ZmyY4SBhtH9YfiYcwLjFwI
5fW8CUwD3gXkTE+LndimNTlQY1pUoU/4WGdLWi2jO/TZ5xnKQpI2xG98zFBgrnt5
rzpI5NJ9EM7vpsy4GJsMXplnc0IeWnFQClRQXCwYdP42uVi4A1fczH6yYvA4pceQ
DY86GfOQCcd/Ielt/8DegxgIS7ArJHCTPmWik7UJbSynHXeSD7CpWDqGtLw6Ja6h
ZNzis0To2JVrPF77vE+/RX8pTmEkx/XYg4qzFFotmDjAkjiHEnE/osB5lOgDGTPD
4wIDAQAB
-----END PUBLIC KEY-----
```

(Curiously, there is also a matching private RSA key included. Could this be necessary to unpack the firmware or is this just a mistake to include, giving the possibility to repack and sign the UPG)?

**Comment by apeppels** [comment]
Thanks so much for the in-depth explanation! 
The keys I've mentioned are from the directory `/ro_data/key`. I don't have shell access, just a file disclosure vulnerability I'm using. I'll see what `/3rd_ro` contains when I get home.

Using the MD5 instead of the keys themselves was a backup strategy the comment I link to suggested. The files are still the AES key and IV in uppercase hex.  Neither seem to work properly. But I'm a bit lost on what other key it might be, and where I might find it on the system.

**Comment by apeppels** [comment]
Okay, I checked and there seems to be no `/3rd_ro/key`. So my guess is the files in `/ro_data/key` are the appropriate AES keys for this firmware one way or another

**Comment by apeppels** [comment]
I've performed a sofware upgrade, the logs dumped over Serv.U port are attached (115200 baud in my case).
[upgrade_summary.txt](https://github.com/openlgtv/epk2extract/files/2564295/upgrade_summary.txt)

They give a great deal of information about the header layouts and show that the keys I dumped are in fact being used. Therefore I'm quite sure that we're simply missing a simple step.

**Comment by smx-smx** [comment]
Hard to tell from that summary, because i don't see anything that hints to the key being valid.
It's not said it's wrong, maybe it's just used in a different way - if they changed the structures or added some fields.
Maybe you can join the Discord channel (link in README) to look at it in a closer way.

**Comment by unautil** [comment]
Hey @apeppels, the correct AES/IV pair is:
```
AES: 1b569aa7d2e4cce66584a7a3d8a45679
IV:  a0e88d5d52a813260d3a34a14aa89416
```
It is the MD5 hash of the key/iv file contents including newline. I can unpack the latest firmware package using it.

Would you mind sharing details of the vulnerability you are using?

**Comment by apeppels** [comment]
Ah fantastic. The way I saw got keys dropped the newline, so indeed I was only hashing the first line.
I'm still in the process of disclosure with Philips. However, see if port 9222 is open.
