### ISSUE TITLE
EPK v3 Key Extraction

### ISSUE THREAD

**Issue by robhunt3r** [openlgtv/epk2extract#2]
Any info about how to get them? I am interested on trinyg to tweak the firmware as 2013 TVs are not WebOS capable...

**Comment by Alisamix** [comment]
Same. Please respond :D

**Comment by Umeaboy** [comment]
If you haven't done so already, read all the necessary pages here:
http://openlgtv.org.ru/wiki/index.php/Wiki_index

**Comment by Umeaboy** [comment]
Search for the firmware of the model that you have on LG's website. Usually under Support ->Guides and Downloads.

**Comment by Umeaboy** [comment]
You can also join #openlgtv on webchat.freenode.net and talk to smxsmx and give him as much detailed information as you can about your TV model and what you have accomplished to try to get access to the TV.
