### ISSUE TITLE
Do you how to extract hisense A6 ROM？

### ISSUE THREAD

**Issue by ykla** [openlgtv/epk2extract#23]
Only two bin files.

File: sysEX file JAN
https://drive.google.com/open?id=16bUSO9acF1XqXHLkqdu7-naz6WBX462N

Please help me. Thanks.

**Comment by smx-smx** [comment]
Not sure, it's a weird format, and it looks like it's partially encrypted with AES ECB
Some files seem unencrypted in there, so you might have some luck with binwalk.

If you have access to a Hisense A6 device you could maybe dump the filesystem or inspect how the update process works to get more knowledge

If cryptographic keys are involved, dumping them will also provide more information

**Comment by Ca11back** [comment]
Hi, have you got any idea about this? I'm also interested in this.

**Comment by ykla** [comment]
@Ca11back See https://www.getdroidtips.com/root-hisense-device/  hisense look likes using MTK tool.
`Download and Install the SP Flash Tool for Mediatek and SPD Flash Tool for Spreadtrum Unisoc devices on your computer.`

**Comment by Ca11back** [comment]
> @Ca11back See https://www.getdroidtips.com/root-hisense-device/ hisense look likes using MTK tool.
> `Download and Install the SP Flash Tool for Mediatek and SPD Flash Tool for Spreadtrum Unisoc devices on your computer.`

Have you tried this already? How to use SPD tools to extract boot.img without get PAC file?

**Comment by zhangtemplar** [comment]
Some issue here. Got three bin files but not pac.
