### ISSUE TITLE
Proper AES key is missing

### ISSUE THREAD

**Issue by p4654545** [openlgtv/epk2extract#24]
After building epk2extract and downloading (and unzipping) the most recent 05.30.65 firmware update for 55B6V (from https://www.lg.com/uk/support/support-product/lg-OLED55B6V) I run and get the following output:

`[anonymous@localhost temp]$ ../epk2extract starfish-dvb-secured-k2l-43.dharug.k2l-4316-05.30.65-prodkey_usb_V3_SECURED.epk 

LG Electronics digital TV firmware package (EPK) extractor version 4.8 (http://openlgtv.org.ru)

Current directory: /home/anonymous/epk2extract/epk2extract/build_linux/temp
Input file: starfish-dvb-secured-k2l-43.dharug.k2l-4316-05.30.65-prodkey_usb_V3_SECURED.epk
Destination directory: .
[EPK3] Platform Version: 3.3.4
[EPK3] SDK Version: 3.3.4
File size: 879343378 bytes

Trying to decrypt EPK header...
Trying known AES keys...
[+] Trying AES Key 1F1E1D1C1B1A19180706050403020100 // BCM35230/early MTK5369 and LG1152
[+] Trying AES Key 4F836AAEB4301F26172A9B0E1120EAF4 // LM1 PDP
[+] Trying AES Key 2F2E2D2C2B2A29281716151413121110 // Saturn7/BCM3556
[+] Trying AES Key 214BF3C129547AF31D32A5ECB4742192
[+] Trying AES Key 6856A0482475A8B41728A35474810203 // new BCM35230
[+] Trying AES Key 212D3B2A5C2D3A2C4D5B234B1A321D2A // new Saturn7/old LM1
[+] Trying AES Key 4EE662C7A2C0917F7328DE73A0836C6B // LM1 LCD
[+] Trying AES Key 7184C9C428D03C445188234D5A827196 // MTK5369 LM6*, LM7*
[+] Trying AES Key 385A992430196A8C44F1985823C01440 // MTK5398 LN5*, LA6*, LA7*
[+] Trying AES Key 4813B5B63C998A2874EF3320684AC8D9 // LG1152 LM79*, LM8*, LM9*
[+] Trying AES Key 14B3623488212250C7C992AACD537447 // LG1154 Netcast LA79*, LA8*, LA9*
[+] Trying AES Key 12C344FDD2871C983CD0FBBC25143974 // LG1154 WebOS UB8*, UB9*
[+] Trying AES Key 2F534ABE34801A36B7DA6B3EB1C04AD4 // M1 LN45*, LN53*, LN54*, LN565*, LA61*, LA643*, MA53*, PN45*, PN65*
[+] Trying AES Key 7B2CA5943D2E752CF58606228C5B2DAD // M1A LB45*, LB55*, LB56*, LB62*, LB64*, LS33*, LY32*, LY33*, LY34*, LY39*, MT44*, MT45*, MT55*, MT75*, PA1000
[+] Trying AES Key 68A284B4953CAD15024BED2C4F852A09 // LM14 UB80*, UB82*, UB83*
[+] Trying AES Key 34CC219D3AFC102433109BBC1DA44095 // M14 EC93*, EG97*, LB60*, LB63*, LB65*, LB67*, LB68*, LB69*, LB7*, LB8*
[+] Trying AES Key 1C966DFA0E5AE9946AAF8D2EC06B9E18 // Realtek - WebOS 3/3.5
[+] Trying AES Key 1B3C76ADD3F5EE6B089DB253747A8CD4 // M16p - LX1.3
[+] Trying AES Key 4ACD2CA8425BBA6C49FD03A174300239 // W19O - LX1.2 WebOS 4
[src/epk.c:245] ERROR: Cannot decrypt EPK content (proper AES key is missing).

Extraction is finished.

[anonymous@localhost temp]$
`

**Comment by smx-smx** [comment]
Hi @p4654545 
Sadly, that means the AES key is missing for your Chipset/OS combo.

The only known way of obtaining the key involves getting root access on your unit.
Contact me on Discord if you're interested
