### ISSUE TITLE
realtek k6lp key is missing

### ISSUE THREAD

**Issue by Zibri** [openlgtv/epk2extract#30]
realtek k6lp key is missing

http://gscs-b2c.lge.com/downloadFile?fileId=0n3epeMB5pzUbOl6vCn9kg

**Comment by smx-smx** [comment]
A working k6lp TV or motherboard is required to retrive the key

**Comment by Zibri** [comment]
I know. And I also know how to root any lgtv model around. But I don't yet have such tv and I wanted to study the firmware, that's why I wanted to extract it.
:D

**Comment by z826540272** [comment]
> I know. And I also know how to root any lgtv model around. But I don't yet have such tv and I wanted to study the firmware, that's why I wanted to extract it.
> :D

How to root the newer lg tv
