### ISSUE TITLE
Unable to extract Sony upg file

### ISSUE THREAD

**Issue by acervenky** [openlgtv/epk2extract#32]
Model : ZX500 Walkman
Format : .upg
Link : https://info.update.sony.net/PA001/NW-ZX500Series_0000/contents/0003/NW-ZX500_0000_V1_20_02_NW_WM_FW.UPG

**Comment by smx-smx** [comment]
I don't think i can do much about that file, unless you can provide a filesystem dump of a working device or an AES key that can decrypt the payload (it's encrypted, and the header doesn't match known formats)

**Comment by acervenky** [comment]
Will try to get a dump, Thank you for your assistance!
