### ISSUE TITLE
Mutiple definitions build issue. GCC 10

### ISSUE THREAD

**Issue by xenoxaos** [openlgtv/epk2extract#33]
$ ./build.sh 
Building epk2extract
-- Configuring done
-- Generating done
-- Build files have been written to: /home/xenoxaos/git/epk2extract/build_linux/obj
[  3%] Built target mfile
[  9%] Built target utils
[ 14%] Built target stream
[ 19%] Built target cramfs
[ 39%] Built target squashfs
[ 46%] Built target lz4
[ 52%] Built target lzma
[ 58%] Built target jffs2
[ 63%] Built target lzhs
[ 65%] Linking CXX executable epk2extract
/usr/bin/ld: libutils.a(util.c.o):/home/xenoxaos/git/epk2extract/src/util.c:29: multiple definition of `modelname'; CMakeFiles/epk2extract.dir/partinfo.c.o:/home/xenoxaos/git/epk2extract/src/partinfo.c:29: first defined here
/usr/bin/ld: libutils.a(util.c.o):/home/xenoxaos/git/epk2extract/src/util.c:31: multiple definition of `part_type'; CMakeFiles/epk2extract.dir/partinfo.c.o:/home/xenoxaos/git/epk2extract/src/partinfo.c:28: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/epk2extract.dir/build.make:315: src/epk2extract] Error 1
make[1]: *** [CMakeFiles/Makefile2:298: src/CMakeFiles/epk2extract.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
Build Failed!

Changing CMake to use GCC9 compiles fine

**Comment by Pablohn26** [comment]
I cannot fix this problem but I can provide [more information about it](https://gcc.gnu.org/gcc-10/porting_to.html). 

### Default to -fno-common

> A common mistake in C is omitting extern when declaring a global variable in a header file. If the header is included by several files it results in multiple definitions of the same variable. In previous GCC versions this error is ignored. GCC 10 defaults to -fno-common, which means a linker error will now be reported. To fix this, use extern in header files when declaring global variables, and ensure each global is defined in exactly one C file. If tentative definitions of particular variables need to be placed in a common block, __attribute__((__common__)) can be used to force that behavior even in code compiled without -fcommon. As a workaround, legacy C code where all tentative definitions should be placed into a common block can be compiled with -fcommon. 

I suppose changing to `-fcommon` would workaround the problem and changing the code would fix this issue.

**Comment by smx-smx** [comment]
Thanks for reporting.
I had already noticed the issue on my end but i hadn't gotten around to fix and push the fix
