### ISSUE TITLE
Found UNKNOWN Package (Magic:  'Phil') is seen when running epk2extract

### ISSUE THREAD

**Issue by Umeaboy** [openlgtv/epk2extract#35]
kristoffer@kristoffer-N550JK:~/Desktop/epk2extract/build_linux$ sudo ./epk2extract /home/kristoffer/Desktop/autorun.upg
[sudo] password for kristoffer: 

LG Electronics digital TV firmware package (EPK) extractor version 4.8 (http://openlgtv.org.ru)

Current directory: /home/kristoffer/Desktop/epk2extract/build_linux
Input file: /home/kristoffer/Desktop/autorun.upg
Destination directory: /home/kristoffer/Desktop
[+] Found UNKNOWN Package (Magic: 'Phil')
malloc(): invalid size (unsorted)
Aborted (SIGABRT)

Is this normal?

**Comment by smx-smx** [comment]
It's clearly abnormal, crashing is not a feature 🙂 
Do you have a link to the firmware you tried it on?

**Comment by Umeaboy** [comment]
https://www.download.p4c.philips.com/files/5/50pus7855_12/50pus7855_12_fus_swe.zip

**Comment by smx-smx** [comment]
It should be fixed now, give it a try

**Comment by Umeaboy** [comment]
That did the trick. Thanks. :)
