### ISSUE TITLE
Rebuild epk2extract to use Unar in favor of Stuffit

### ISSUE THREAD

**Issue by Umeaboy** [openlgtv/epk2extract#36]
I'm no expert on how this program unpacks firmware, but I think Unar is a good alternative to the outdated Stuffit.
I'd like to suggest that epk2extract in the future can use Unar as a build requirement to increase the number of firmwares that can be extracted.

**Comment by Umeaboy** [comment]
https://launchpad.net/ubuntu/trusty/+package/unar

**Comment by smx-smx** [comment]
I have no idea what you're talking about
epk2extract doesn't use stuffit whatsoever

closing
