### ISSUE TITLE
Pack EPK v3

### ISSUE THREAD

**Issue by mycop5** [openlgtv/epk2extract#70]
How to make EPK v3 firmware after made change?

**Comment by smx-smx** [comment]
It's not possible. We do not have the required signing keys, so it would be pointless to even try.

**Comment by mycop5** [comment]
> It's not possible. We do not have the required signing keys, so it would be pointless to even try.

Not sure taht understand.
We have key for extract. We can extract. Why just cant pak with same key?
As i understand the only problem is dismiss of digital signature. But it can be passed if you enabling debug on tv Service menu.

**Comment by smx-smx** [comment]
No, you cannot bypass signature verification. Flashing a signed partition without the proper signature WILL result in a brick.

**Comment by mycop5** [comment]
> No, you cannot bypass signature verification.
Did you try to flash unsigned firmware with enabled Debug mode or you missed my words about it?
Can you tell litle bit more about succes or fail?

**Comment by mksy** [comment]
> flash unsigned firmware with enabled Debug mode

do you think developers from a large international Korean company are so stupid? there are several levels of system integrity checks at startup. Debug mode has nothing to do with it (even USB access key)

**Comment by mycop5** [comment]
> do you think developers from a large international Korean company are so stupid?

Dude... I dont ask about Korean smarts ability. 
I just ask about "pack" firmware,  and ask exactly YOU about trying in debug mode. Cuz my information (especialy about USB key...and turned ON debug mode) litle bit differente.
Just  answer and dont be shy  to say you didnt try it but not start holywar.

**Comment by throwaway96** [comment]
Are you saying you have an AccessUSB? That would be... interesting. But we're quite familiar with debug mode; I have a substantial number of webOS boards, and they're (almost) all in debug mode.

You're aware that the bootloader source (for MStar and Realtek SoCs, anyway) is available, right? Perhaps you should take a look and see what debug mode actually affects. Even LG's development firmware is signed; why would they bother (with a separate key, even) if it were so easy to bypass signature verification?

You shouldn't need to construct an EPK to see what happens when verification fails. Just modify one of the signed partitions from within webOS. If the modification is small enough, it may successfully boot *a few times* due to the way verification works. But after verification fails once, it won't boot again until everything is restored to a signed version. Anyway, if you do have debug mode enabled, you'll at least theoretically be able to recover. (And no, I've never tried this.)

Try it and find out. You've been warned.

**Comment by mycop5** [comment]
> Try it and find out. You've been warned.

Thank you very much for detailed answer. This exactly what i need to know. (However...as i understand you talk about old SOC's) But i think you are right. It may be fail.
Unfortunely at this time i have one single board with my TV =) And FAIL may price me cost. Thats why i learn much as i can. I will try, when i found a way to roll back. 
I can start wih flashing original firmware  (for example some tv 2019 year have same hardware parts of 2020, but diferent with software and  cuted out DTS audio...)
Do you know, webos or bootloader have some like Failsafe mode? (recovey\dfu\etc) Actulay dont mind how it realy called. The way to flash "firmware" back when tv is bricked. If it need to solder few wired to have console access im ready to rock.

**Comment by throwaway96** [comment]
MStar (part of Mediatek now) and Realtek SoCs are still in use in 2023 models. Pretty much each SoC has its own RSA key for firmware verification (there are some in the `keys` directory of this repo), so you're not going to be able to use firmware from a different model.

It may be possible to access the eMMC directly, but I don't know anyone who has tried it. It's in a BGA package, so you'll have to hope the relevant signals are brought out somewhere accessible.

There is information about serial access in [this guide](https://gist.github.com/throwaway96/827ff726981cc2cbc46a22a2ad7337a1). When debug mode is enabled, you can access the U-Boot (on MStar/Realtek SoCs) or lxboot (LX SoCs) prompt by holding certain keys during boot. (Try enter, escape, or \`.) You can theoretically recover a bricked system from there.

If you're interested in DTS, you might want to take a look at [this](https://github.com/lgstreamer/dts_restore).

**Comment by mycop5** [comment]
> so you're not going to be able to use firmware from a different model.

even if soc same (or almost same?)

> There is information about serial access in [this guide](https://gist.github.com/throwaway96/827ff726981cc2cbc46a22a2ad7337a1).

thanks its very useful.

> When debug mode is enabled, you can access the U-Boot (on MStar/Realtek SoCs) or lxboot (LX SoCs) 

1.only in debug mode? (firmware corruption or  failed flash process  may apper in release mode. So... there is no way to Flash it againt in this case?)

>prompt by holding certain keys during boot.

2.  which keys need to hold? Some like on smartphone i guess?

> If you're interested in DTS, you might want to take a look at [this](https://github.com/lgstreamer/dts_restore).

Yes i know about this limited method. It enoug for loking stereo on TV speakers. But its more important to send Bitsream via spdif or hdmiARC.

**Comment by throwaway96** [comment]
> even if soc same (or almost same?)

Generally, each SoC has its own key. I made a [new version of `AES.key`](https://github.com/openlgtv/epk2extract/blob/acfb38549d758a71d6679a821fd888c0d6ebe654/keys/AES.key) that tries to make it clearer which SoC each key is for.

> 1.only in debug mode? (firmware corruption or failed flash process may apper in release mode. So... there is no way to Flash it againt in this case?)

Depending on what part of the boot process fails, you may (theoretically) be able get to the U-Boot prompt on certain platforms. LG likely has other means of recovering from such a situation.

> 2. which keys need to hold? Some like on smartphone i guess?

The ones I listed: MStar uses \` (grave accent, ASCII 0x60), Realtek uses escape, and LX uses enter. This should work on a hardware UART/RS-232C port (unless it's routed to MICOM or something) as well as PL2303 (as long as it's not on a USB 3.x port). Here's how it's implemented in MStar's U-Boot (`CONFIG_SECURITY_BOOT` is defined):
```c
#ifdef CONFIG_SECURITY_BOOT
	if ((DDI_NVM_GetDebugStatus() != RELEASE_LEVEL))
#endif
	{
		for (i=0; i<20; ++i) {
			if (tstc()) {
				key = getc();
				if (key == 0x60)
					break;
			}
			udelay (10);
		}
	}
```
If `key` is not  `0x60` after this, it continues with a normal boot.
